### ISSUE TITLE
If all samples are male, the program exists with error msg "Something went wrong with the kepsample female command"

### ISSUE THREAD

**Issue by saliluo** [genepi/imputationserver#1]
It should allow all samples to be male.

**Comment by PaulCotney** [comment]
It appears that the when the b2 array is of zero length, meaning no female entries in the non-par2 region, then an array of length zero is produced for the parameter list(line 405-405 in VcfFileUtil.java), which is fed to the keepsample's execute method (ln 413) which raises a non-zero causing an exception to be returned (414-415). I know that the file that is supposed to be produced (*-f.vcf) is utilized later so I am not sure if an empty file would not cause another issue. I would create a pull request, but I really don't have any easy way to test the code.

**Comment by seppinho** [comment]
Hi guys, thanks for letting us know. @lukfor and I are currently working on this and it should be solved by Monday.
