### ISSUE TITLE
HLA type results are disappear in Genotype Imputation HLA

### ISSUE THREAD

**Issue by asangphukieo** [genepi/imputationserver#108]
I noticed that the format of Genotype Imputation HLA output has changed!

1. variant position and allele are used for the variant name instead of RS ID
2. HLA typing result are disappear in chr6.dose.vcf.gz and chr6.info.gz files

How can I get these information back?

Many thanks.
Best,

**Comment by seppinho** [comment]
Hi,
MIS provides several worfklows via **Run**: "Genotype Imputation (Minimac4)" vs "Genotype Imputation HLA (Minimac4)". Your API example above uses the Minimac4 workflow.

**Comment by asangphukieo** [comment]
Thank you for your clarification

https://imputationserver.sph.umich.edu/api/v2/jobs/submit/minimac4

changes to 

https://imputationserver.sph.umich.edu/api/v2/jobs/submit/imputationserver-hla

works now
