### ISSUE TITLE
HRC panel for genotype imputation not working yet ??

### ISSUE THREAD

**Issue by diyanath91** [genepi/imputationserver#138]
Hi, 

Any idea when the HRC panel for genotype imputation will be up again? The homepage said it will be back online on 12th April but still cannot see it in the dropdown menu.

Thanks in advance.

**Comment by lukfor** [comment]
Hi. Thanks, could you please try again? It should be available now.

**Comment by diyanath91** [comment]
Hi, Yes it's working now. Thanks a lot !!
