### ISSUE TITLE
SSL Connection Error When Accessing Imputation Server Website

### ISSUE THREAD

**Issue by yu-tong-wang** [genepi/imputationserver#145]
I'm unable to access the Imputation Server website (imputationserver.sph.umich.edu) due to SSL connection errors. The issue persists across different networks and browsers. Error messages encountered:

Chrome on Wifi:
```
This site can't be reached
imputationserver.sph.umich.edu took too long to respond.
ERR_CONNECTION_TIMED_OUT
```

Chrome on mobile data:
```
This site can't provide a secure connection
imputationserver.sph.umich.edu sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

Safari on Wifi:
`Safari can't open the page because the server where this page is located isn't responding. 
`

I've tried to clear browser cache and cookies, and this didn't help. Based on the error messages, it seems there might be an issue with the server's SSL certificate or configuration. The timeout error suggests there could also be server availability problems.

Can you please check the server status and SSL certificate configuration? Let me know if you need any additional information from my end to investigate this issue.

**Comment by seppinho** [comment]
We are now live again.
Best
