### ISSUE TITLE
Server API requests

### ISSUE THREAD

**Issue by amarcket** [genepi/imputationserver#15]
I have been doing some work with the Michigan Imputation Server API lately and there are a couple of feature requests I would like to suggest:

1. Passwords for output files should be able to be requested via the API or the user should be able to set the password for a job during job submission. Being forced to pull the password out of your email does not allow the user to easily automate the unlocking of the resulting dosage files.

2. Allow the user to specify the length of time that an API token is valid for. At the moment it looks like the API token stops working after about a day, forcing the user to revoke it and create a new token. This also breaks any efforts at automating interactions with the imputation server.

Thanks!

**Comment by seppinho** [comment]
Thanks again for the feedback. Both issues/ feature requests have been integrated in v1.1.15
