### ISSUE TITLE
Compile Failure

### ISSUE THREAD

**Issue by SunProg** [genepi/imputationserver#17]
On the imputation server docker, 

I tried to compile this project with maven, but it failed.

I haven't edited any code in the project, but, it doesn't work.

It failed in the test course, failures are following.

```
`Results :
 
 Failed tests:   testPipelineWithEagle(genepi.imputationserver.steps.ImputationTest)
   testCompareInfoAndDosageSize(genepi.imputationserver.steps.ImputationTest)
testPipelineWithEaglePhasingOnly(genepi.imputationserver.steps.ImputationTest)
testPipelineWithPhasedHg19ToHg38(genepi.imputationserver.steps.ImputationTest)
testPipelineWithEagleHg19ToHg38(genepi.imputationserver.steps.ImputationTest)
testPipelineWithSFTP(genepi.imputationserver.steps.ImputationTest): expected:<true> but was:<false>
testPipelineWithPhasedAndNoPhasingSelected(genepi.imputationserver.steps.ImputationTest)
   testPipelineWithPhased(genepi.imputationserver.steps.ImputationTest)
testWriteTypedSitesOnly(genepi.imputationserver.steps.ImputationTest)
testPipelineWithPhasedHg38ToHg19(genepi.imputationserver.steps.ImputationTest)
testPipelineWithEagleHg38ToHg19(genepi.imputationserver.steps.ImputationTest)
 testPipelineWithEagleHg38ToHg38(genepi.imputationserver.steps.ImputationTest)
testPipelineWithEagleAndR2Filter(genepi.imputationserver.steps.ImputationTest)
 testPipelineWithHttpUrl(genepi.imputationserver.steps.ImputationTest)
 testPipelineWithPhasedAndEmptyPhasing(genepi.imputationserver.steps.ImputationTest)

 Tests run: 65, Failures: 15, Errors: 0, Skipped: 0`
```

**Comment by lukfor** [comment]
Which Operating System are you using? All binaries (e.g. Minimac4 and Eagle2) used in the pipeline are compiled on Linux. We test the build with Ubuntu on travis and all tests passed.

**Comment by SunProg** [comment]
> Which Operating System are you using? All binaries (e.g. Minimac4 and Eagle2) used in the pipeline are compiled on Linux. We test the build with Ubuntu on travis and all tests passed.

First of all, thank you for replying me.

I tested in the imputation server docker with my mac.

Building is well done but, in the test procedure, it returned failure message.

**Comment by seppinho** [comment]
I'm closing this issue for now. When compiling locally please use maven or have a look at our travis tests.
