### ISSUE TITLE
Are indels excluded ?

### ISSUE THREAD

**Issue by orr161** [genepi/imputationserver#21]
According to the documentation, the exclusion criteria are [a] invalid alleles [b] duplicates [c] indels [d] monomorphic sites, [e] allele mismatch [f] SNP call rate < 90%.

The HRC does not have indels, but the 1000G does. 
Are all indels removed in the QC step even when 1000G imputation is selected?
Is it possible to skip the indel exclusion ?

Thanks.

**Comment by cfuchsberger** [comment]
Exclusion criteria are only applied to the input GWAS data. The imputed 1000G data will include SNVs, SVs, and InDels.
Best,
Christian
