### ISSUE TITLE
MIS not generating the additional EmpiricalDose

### ISSUE THREAD

**Issue by orr161** [genepi/imputationserver#26]
file that should be generates with the Minimac 4 command that is called in the MIS pipeline (--meta). This file is required for meta imputation downstream. 

This is a known issue with some versions of the Minimac 4 binaries, and discussed in their github, so I assume this is one of these versions that is implemented in the MIS.

**Comment by orr161** [comment]
After testing different minimac4 versions, they all generated the EmpiricalDose file while called with --meta outside of the MIS but not when ran the MIS pipeline (using the same binaries).

I can confirm that the problem is with MIS and not Minimac4. I suspect that the EmpiricalDose file may be lost at the stage of the merging of the chunks post imputation.

Do you have an idea of how can I fix that?

Thanks.

**Comment by seppinho** [comment]
Meta option is provided when using the latest MIS version.
