### ISSUE TITLE
Password mismatch

### ISSUE THREAD

**Issue by orr161** [genepi/imputationserver#32]
How can I run a command line job with no password for the output zip file? or to specify the password beforehand? 

I ran 115 jobs on my locally installed hadoop cluster MIS (latest version). 
I unzipped them using a script I wrote to retrieve the passwords from the log files, but 5 of them rejected the password. I also failed when tried to manually enter the passwords, and noticed that all 5 passwords that failed are pretty short (e.g. t or BiPx) and I suspect they were not printed correctly to the log file due to special characters that they included, and only part of the password is printed to the log file. I can't use these 5/115 output files not and will have to re-run them. I would rather avoid such issues and have them either not password protected, or set the password myself.

**Comment by seppinho** [comment]
Password can be set when using the API: https://imputationserver.readthedocs.io/en/latest/api/
hope this helps.
sebastian
