### ISSUE TITLE
Jobs fail with no helpful error message

### ISSUE THREAD

**Issue by oskarvid** [genepi/imputationserver#33]
The output from the job is in the pastebin link below.

I'm testing out the docker version of the server now, this is how I start it:  
`docker run -d -p 8080:80 -v $(pwd):/data/ genepi/imputationserver:v1.2.4`

I'm starting a job from the web interface with [these files](https://github.com/genepi/imputationserver/files/4244981/tiny-chr4-inputs.tar.gz). I get the same error if I start a job manually with `docker exec -ti name-of-container cloudgene run imputationserver@1.2.4 --files /data/test-data/data/simulated-chip-1chr-imputation/ --conf /etc/hadoop/conf --population eur`

The files I attached have worked before when I tested the server in March last year. I have also tried the supplied test files in the `test-data` directory but they produce the same error message. What could be wrong?

https://pastebin.com/Dvc1XrJW

**Comment by seppinho** [comment]
Can you try the latest version? We had some problems with the default java version.

**Comment by oskarvid** [comment]
> Can you try the latest version? We had some problems with the default java version.

I finally tried the latest version and I ran into one issue; the job ran fine until it reached the tabix step. It failed there because the tabix binary, and all other binaries in the `apps/imputationserver/1.2.7/bin` directory, didn't have execute rights. I simply ran `chmod +x` on all binaries for good measure, and that fixed it.
