### ISSUE TITLE
Issue regarding the access to UCSC database

### ISSUE THREAD

**Issue by LinduniR** [genepi/imputationserver#37]
Hi,
I tried to get output files for example data using  $ GenEpi -g example -p example -o ./  command. But, I got an error:
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'genome-mysql.cse.ucsc.edu' (timed out)")

I searched for "genome-mysql.cse.ucsc.edu'. But, it is not available.

So, It would be really appreciated if you can give any suggestion to overcome this problem. 

Thank you in advance.

**Comment by seppinho** [comment]
wrong repo. closing the issue.
