### ISSUE TITLE
API: Add Rsq filter

### ISSUE THREAD

**Issue by jangehlen** [genepi/imputationserver#40]
Hi, 
I was wondering whether it would be possible to add the minimum Rsq filter found in the pretty WebUI option to the API? This would cut down some major downstream analysis time and storage space for us, since we are mainly interested in higher confidence imputed variants.

**Comment by lukfor** [comment]
Thank you for your feedback! 👍 We added the flag. Please see https://imputationserver.readthedocs.io/en/latest/api/#job-submission for details.

**Comment by jangehlen** [comment]
Thank you very much! :+1:
