### ISSUE TITLE
Download error: {"success":false,"message":"number of max downloads exceeded."}

### ISSUE THREAD

**Issue by Steven-Shixq** [genepi/imputationserver#49]
Hi,
I can't download Imputation Results, as it remedied me the error below:

> {"success":false,"message":"number of max downloads exceeded."}

my download page:
![image](https://user-images.githubusercontent.com/37492848/92444973-3740ff00-f1e6-11ea-8832-ad51d7ffa1ab.png)
when I click *chr_15.zip* to download, it pops up just like this:
![image](https://user-images.githubusercontent.com/37492848/92445243-9ef74a00-f1e6-11ea-90ab-199fa7a5a78a.png)

How can I download the Imputation results?

Thank you in advance.

**Comment by Hagay-Ladany** [comment]
It happened to me too, I don't know why. 
Maybe because the download speed was too slow and every download has a time limit or a limited number of requests.

**Comment by dongdongyaa** [comment]
It happened to me too.I am looking for the solutions to solve this download problem.So could you download the imputation result?If you find some ways, could you help me. I would appreciate it

**Comment by Hagay-Ladany** [comment]
I could not find any information about how to download the exceeded files. I had to restart the imputation again.
you can try to download the file with a fast internet connection to avoid reaching the time limit.

**Comment by dongdongyaa** [comment]
> I could not find any information about how to download the exceeded files. I had to restart the imputation again.
> you can try to download the file with a fast internet connection to avoid reaching the time limit.

Thank your reply! I will try again!

**Comment by lukfor** [comment]
Due to security concerns, we limited the number of downloads. This error occurs, when the maximal number of downloads exceeds. In case you need an extension, please let [us](https://imputationserver.sph.umich.edu/index.html#!pages/contact) know.
