### ISSUE TITLE
hg38 reference: strand flips

### ISSUE THREAD

**Issue by meghanasp21** [genepi/imputationserver#53]
Hi.

I am trying to use the webserver MIS Minimac4 server to impute samples with hg38 aligned variants. I have double-checked that there are no strand flips; however, I keep getting the error of more than 100 obvious strand flips. I have the information below. Is there another way to check the strand flips so I can complete imputation? Any help would be appreciated.

**Quality Control**
Uploaded data is hg38 and reference is hg19.

Lift Over

Skip allele frequency check.

Calculating QC Statistics

Statistics:
Alternative allele frequency > 0.5 sites: 0
Reference Overlap: 92.71 %
Match: 4,849,194
Allele switch: 1,205,271
Strand flip: 74
Strand flip and allele switch: 52
A/T, C/G genotypes: 850,564
Filtered sites:
Filter flag set: 0
Invalid alleles: 0
Multiallelic sites: 0
Duplicated sites: 657
NonSNP sites: 0
Monomorphic sites: 136
Allele mismatch: 42,917
SNPs call rate < 90%: 90,636

Excluded sites in total: 134,472
Remaining sites in total: 6,814,393
See snps-excluded.txt for details
Typed only sites: 546,309
See typed-only.txt for details

Warning: 1 Chunk(s) excluded: < 3 SNPs (see chunks-excluded.txt for details).
Warning: 2 Chunk(s) excluded: reference overlap < 50.0% (see chunks-excluded.txt for details).
Remaining chunk(s): 161
Error: More than 100 obvious strand flips have been detected. Please check strand. Imputation cannot be started!

Thanks,
Meghana

**Comment by klingsly** [comment]
I also encountered the same problem, did you solve your problem?

**Comment by seppinho** [comment]
Please have a look at the Pre-Imputation Tool here to fix strand flips: https://www.well.ox.ac.uk/~wrayner/tools/
