### ISSUE TITLE
Jobs do not start

### ISSUE THREAD

**Issue by nickhir** [genepi/imputationserver#64]
I am currently trying to impute some VCF files, via the web interface, and everything works as intended, until the VCF file is uploaded. 
The documentation says that “Input Validation and Quality Control are executed immediately to give you feedback about the data-format and its quality”.
However, for my jobs this is not the case, the site simply stays blank and simply looks like this:
![image](https://user-images.githubusercontent.com/49643134/133772141-d442e434-b8fe-48ec-9dd7-54c062453693.png)

I thought that maybe there are currently no resources available, but this Job is now waiting for quite a long time (over a day) with no change. 
I am only writing, because a couple of months ago, I also ran a job on the Michigan imputation server and everything worked flawlessly (I am using the same vcf files now), so I thought that maybe there is a problem on the server site of things.

Any ideas what might be the problem here? 
Any help is much appreciated.

**Comment by enigmargs** [comment]
I'm facing the same issue. My jobs are submitted (trying one chromosome to start with). 
I'm new to bioinformatics in general and I'm not sure where I'm going wrong!

Any help?
