### ISSUE TITLE
Imputation on chromosome 14 failed. Imputation was stopped.

### ISSUE THREAD

**Issue by RichardB96** [genepi/imputationserver#72]
I am trying to impute a dataset aligned to the HRC reference panel on minimac4 using that same HRC panel, however every job I run gets to the prephasing/imputation phase and stops with the error:

> Imputation on chromosome 14 failed. Imputation was stopped.

​There isn't any error files or much to try and diagnose this problem from my end - I am unsure if chr14 is the first to be imputed and this is indicative of issues with my dataset, or else they are imputed in order and there is just something wrong with chr14 etc. 
If this is something you've come across and/or you know what the problem could be it would be very helpful!

**Comment by RichardB96** [comment]
error in data pre-processing, nothing server side

**Comment by Fiwx** [comment]
@RichardB96 what was the error in pre-processing?
