### ISSUE TITLE
How to get the docker to push jobs to Hadoop

### ISSUE THREAD

**Issue by rozaimirazali** [genepi/imputationserver#8]
Hi there!

We managed to get the docker to run inside a local VM but when we tried to link it to our Hadoop clusters, it is not connecting. Instead, the jobs are running WITHIN the docker/VM environment.

When we tried to ping our Hadoop clusters IP add from within the docker env, we are able to do it. So, the docker can "see" the Hadoop clusters but I don't know why the jobs are not being "push" to the clusters. 

It seems that the Imputation Server is ignoring the IP in the config files (/etc/haddop/conf)    
 
What we did:
 
**Changed the IP in mapred-site.xml**

```
<property>
     <name>mapred.job.tracker</name>
     <value>172.32.62.64:8021</value>
</property> 
```
 
**Changed the IP in core-site.xml**

```
<property>
      <name>fs.defaultFS</name>
      <value>hdfs://172.17.0.3:8020</value>
</property>
```

 
**Changed the values in hdfs-site.xml**

```
<property>
       <name>dfs.datanode.data.dir</name>
       <value>hdfs:///user/imputation/data</value>
</property>
```

 
Is there some other config files that we need to edit so that we can fire the jobs to our Hadoop env instead of running locally within the docker container?
 
Could you please help?

Thanks,
Rozaimi

**Comment by rozaimirazali** [comment]
We managed to get the docker running on our local VM but when we tried to link it to our Hadoop clusters, it is not connecting. FYI, our Hadoop is able to make ping to outside.

What we did:
 
Changed the IP in mapred-site.xml
<property>
<name>mapred.job.tracker</name>
                <value>172.32.62.64:8021</value>
  </property>
 
Changed the IP in core-site.xml
<property>
<name>fs.defaultFS</name>
                <value>hdfs://172.17.0.3:8020</value>
  </property>
 
Changed the <name> and <property> values in hdfs-site.xml
<property>
     <name>dfs.datanode.data.dir</name>
     <value>hdfs:///user/imputation/data</value>
  </property>
</configuration>

Error:


18/05/14 11:14:59 Executing Job installation....
18/05/14 11:14:59   Preparing Application 'Michigan Imputation Server'...
18/05/14 11:14:59   Installing Application imputationserver...
18/05/14 11:14:59  Installation failed.
18/05/14 11:14:59 Unknown protocol: org.apache.hadoop.hdfs.protocol.ClientProtocol
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.getProtocolImpl(ProtobufRpcEngine.java:557)
at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:596)
at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2211)

18/05/14 11:14:59 Cleaning up uploaded local files...
18/05/14 11:14:59 Cleaning up temporary local files...
18/05/14 11:14:59 Cleaning up temporary hdfs files...
18/05/14 11:14:59 Cleaning up hdfs files...
</code></pre>

**Comment by rozaimirazali** [comment]
Since you guys are developing a new version that can interact directly with local hadoop, this question is no longer relevant.

**Comment by jjfarrell** [comment]
Is there a timeline for the new version that will push jobs to a Hadoop cluster?

Also is the inability to push jobs to Hadoop limited to the docker version? Is the non-docker version of ImputationServer able to push jobs to a local Hadoop Cluster?
