### ISSUE TITLE
Web server: "At least 50 samples must be uploaded"

### ISSUE THREAD

**Issue by enabieva** [genepi/imputationserver#81]
When using the web server, I get an error: "Input Validation At least 50 samples must be uploaded".  There is only one sample in the vcf.  I didn't get when I tried with a different file (also single-sample) a few weeks ago.
In documentation, I don't see any requirement for at lest 50 samples (which seems strange anyway), and I suspect the issue may in fact be different.
Could you please comment on this error?

**Comment by cfuchsberger** [comment]
Correct, server works also with 1 sample only. However, there is a setup cost involved for each imputation - recently MIS got hit by a large number of very small imputation jobs which slowed down the server. Until we have implemented a more efficient way to handle this type of imputation, we will require min samples.

**Comment by Irtazaraza** [comment]
Will this be also true for the docker deployment of the server?

**Comment by seppinho** [comment]
No, that's only true for the MIS instance.
