### ISSUE TITLE
TopMED output only for 1 chromosome (Input files are 22)

### ISSUE THREAD

**Issue by ImFran** [genepi/imputationserver#87]
Good evening to everyone, 

I hope that it will be not a dummy question. 
I used TopMED Imputation Server to impute 3859 samples and more than 900'000 variants, from chr 1 to chr 22 (genotyped with Illumina Infinium Global Screening Arrays).
The quality controls step returned these warnings;

__**Warning:** 3 Chunk(s) excluded: < 3 SNPs (see [chunks-excluded.txt](https://imputation.biodatacatalyst.nhlbi.nih.gov/results/job-20220813-083249-646/statisticDir/chunks-excluded.txt) for details).
**Warning**: 251 Chunk(s) excluded: at least one sample has a call rate < 50.0% (see [chunks-excluded.txt](https://imputation.biodatacatalyst.nhlbi.nih.gov/results/job-20220813-083249-646/statisticDir/chunks-excluded.txt) for details).
**Warning**: 43 Chunk(s) excluded: reference overlap < 50.0% (see [chunks-excluded.txt](https://imputation.biodatacatalyst.nhlbi.nih.gov/results/job-20220813-083249-646/statisticDir/chunks-excluded.txt) for details).
**Remaining chunk(s):** 1__

Before performing the imputation, I used PLINK v.1.9 to run different quality controls:
- filter variants and samples with low call rate genotyping <90% (--geno 0.10 --mind 0.10); 
- perform the Hardy-Weimberg exact test (--hwe 1e-10);
-  remove region in extended LD;
- filter variants with a MAF < 1% (--maf 0.01)

I am not sure about the reason why just one chunk remains and then only one chromosome is imputed. 
Thank you for any kind of help or suggestion to fix this error. 

Francesca

**Comment by seppinho** [comment]
Hi Francesca,
I would recommend to run your input data through the [HRC or 1000G Imputation preparation and checking" tool](https://www.well.ox.ac.uk/~wrayner/tools).
There's also a section included regarding Topmed usage ("Usage with the TOPMed reference panel").
