### ISSUE TITLE
question about reference genome

### ISSUE THREAD

**Issue by aheritas** [genepi/imputationserver#92]
I have successfully installed a local version of the Michigan Imputation Server using the docker image (thanks!). I am able to run the Hello Cloudgene. However, I am unable to run the output from a mapping + variant calling nf-core pipeline named Sarek.
This is the code I am using to produce the VCF:

nextflow run nf-core/sarek --input /data/michigan/samplesheet.csv --outdir gatk_results_dir --genome GATK.GRCh37 -profile docker --max_memory 60.GB -r 3.0.2  --tools strelka 

The input data is a pair of FASTQ files from a sample low-pass -sequenced. The reference genome used is from iGenomes (https://nf-co.re/usage/reference_genomes).

I am then splitting the output VCF per chromosome and submitting it to the MIS using HapMap2 as reference panel.
The error I am getting in the Michigan Imputation Server is the following:

Warning: 154 Chunk(s) excluded: reference overlap < 50.0% (see [chunks-excluded.txt](http://192.168.70.50:8082/results/job-20221026-142905-764/statisticDir/chunks-excluded.txt) for details).
Remaining chunk(s): 0
Error: No chunks passed the QC step. Imputation cannot be started!

So, I understand that there are discrepancies between the reference genome used in the MIS and the reference genome the sarek pipeline uses. I am, however, unsure on to how to troubleshoot this. I would appreciate your insights.

**Comment by seppinho** [comment]
Yes this means there's no overlap between your VCF data and the reference panel.  The Hapmap zip file includes  a legend file, you could manually compare some of the sites from your data with this file to see what's going on.

**Comment by aheritas** [comment]
Dear Sebastian, thank you for the suggestion. I followed the steps with William Rayner tool but it does not produce the input files necessary (-updated.bed) to run the script `Run-plink.sh`. I tested this with both `1000G` and `HRC`. I outline here the steps I undertake, but I have the feeling the problem may lie in the conversion of VCFs to plink binary format. I also tested this with both `plink2` and `plink 1.9` and the problem persists. 

#### 1. Convert VCF to PLINK bed-bim-fam

`plink --vcf /data/michigan/SAMPLE_1.strelka.variants.vcf.gz --make-bed --out SAMPLE --allow-extra-chr  --autosome --double-id`

#### 2. Make .freq file

`plink --freq --bfile SAMPLE --out SAMPLE_freq --allow-extra-chr --autosome
`
#### 3. Run HRC-1000G-check-bim.pl tool

`perl HRC-1000G-check-bim.pl -b SAMPLE.bim -f SAMPLE_freq.frq -r 1000GP_Phase3_combined.legend -g -p ALL` # At this step it does not generate the (SAMPLE-updated.bed file which is the input for the next step)

#### 4. Run the output script (Run-plink.sh)

`sh Run-Plink.sh `
where error is: `"Error: Failed to open /data/michigan/data_preparation/SAMPLE-updated.bed." `

Since the VCF to PLINK binary is the only step not listed in yours and William Rayner's websites, I suspect I might have a problem there, but I appreciate if you have any suggestions. I would like to standardize how the VCF output of `nf-core sarek`, which is what I am using as an input, could be used as an input for the Michigan Imputation Server.  Thank you!

**Comment by aheritas** [comment]
I was able to solve this by preparing VCF files with this: http://apol1.blogspot.com/2014/11/best-practice-for-converting-vcf-files.html and then continuing with William Rayner tool. Thanks!
