### ISSUE TITLE
Unable to upload more than 1 file via sftp

### ISSUE THREAD

**Issue by theandyb** [genepi/imputationserver#96]
I am able to successfully add sftp links to more than one file through the dialogue (each link having its own line):
![sftp_error_1](https://user-images.githubusercontent.com/7965339/212749489-2778a83e-6134-4142-ba8f-c78e425e2887.png)
![sftp_error_2](https://user-images.githubusercontent.com/7965339/212749574-135a34bb-8fdd-4a09-8026-88e9cc00e6f7.png)

but upon submitting the job it looks as though Imputation Server attempts to download from a path composed from pasting the provided paths into one string:
![sftp_error_3](https://user-images.githubusercontent.com/7965339/212750054-ef73ee8e-1326-423e-a103-84d5738f7881.png)

**Comment by seppinho** [comment]
sftp feature is deprecated. I'm closing this issue.
